ln -s /data/home/yuanhaoc/DPO_Data/ DPO_Data
ln -s /data/home/yuanhaoc/eval_results_all eval_results_all
ln -s ../DiffSynth_Studio_v1/collect_train_data/ train_json
ln -s /data/home/yuanhaoc/trained_models/train/ models/train
ln -s /data/home/yuanhaoc/Wan-AI/ models/Wan-AI
ln -s /data/home/yuanhaoc/dpo_overfitting_results/ dpo_overfitting_results
ln -s /data/home/yuanhaoc/videophy/eval_all_score eval_all_score
ln -s /data/home/yuanhaoc/pretrained/ models/pretrained
ln -s /data/home/yuanhaoc/DiffSynth_Studio_v1/collect_train_data/ json_files