accelerate launch \
  --num_processes 8 \
  --num_machines 1 \
  --mixed_precision bf16 \
  examples/wanvideo/model_training/train_PhyGDPO.py \
  --dataset_base_path ../PhyAugPipe/T2V_data/VIDGEN-1M_unzip/ \
  --height 480 \
  --width 832 \
  --dataset_repeat 10 \
  --model_id_with_origin_paths "Wan-AI/Wan2.1-T2V-1.3B:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.1-T2V-1.3B:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.1-T2V-1.3B:Wan2.1_VAE.pth" \
  --learning_rate 1e-5 \
  --total_training_steps 3000 \
  --remove_prefix_in_ckpt "pipe.dit." \
  --output_path "./models/train/Wan2.1-T2V-1.3B_PhyGDPO" \
  --lora_base_model "dit" \
  --lora_target_modules "q,k,v,o,ffn.0,ffn.2" \
  --lora_rank 48 \
  --skip_download \
  --dataset_base_path_positive ../PhyAugPipe/T2V_data/VIDGEN-1M_unzip/ \
  --dataset_base_path_negative ../PhyAugPipe/DPO_data/Wan1.3B/ \
  --save_every_steps 500 \
  --log_every_steps 10 \
  --gradient_accumulation_steps 1 \
  --dpo_beta 1000 \
  --use_gradient_checkpointing_offload \
  --dataset_metadata_path ../PhyAugPipe/videophy/evaluated_score/train_part_0_1.3B_seed_0/final.csv \
  --alpha_min 0.5 \
  --k_alpha 5.0 \
  --b_alpha 0.5 \
  --k_gamma 2.0 \
  --b_gamma 0.4 \
  --lambda_gamma 0.6